# Generated by Django 6.0.1 on 2026-01-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='store_produ_brand_aa2434_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['base_price'], name='store_produ_base_pr_252ebd_idx'),
        ),
    ]
