# Generated by Django 6.0.1 on 2026-01-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_store_produ_name_5e57da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tax_id',
            field=models.CharField(blank=True, help_text='CUIT/RUT para facturación', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_tax_id', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='store.order')),
            ],
        ),
    ]
