# Generated by Django 6.0.1 on 2026-01-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_number',
            field=models.CharField(blank=True, help_text='Número de cliente interno', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='iva_condition',
            field=models.CharField(blank=True, choices=[('RI', 'Responsable Inscripto'), ('MONO', 'Monotributista'), ('EX', 'Exento'), ('CF', 'Consumidor Final'), ('', 'No especificado')], default='', help_text='Condición frente al IVA', max_length=10),
        ),
    ]
