# Generated by Django 6.0.1 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customuser_client_number_customuser_iva_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Contraseña en texto plano (solo para uso administrativo)', max_length=50, null=True),
        ),
    ]
