# Generated by Django 6.0.1 on 2026-01-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customuser_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, help_text='Domicilio', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_type',
            field=models.CharField(blank=True, choices=[('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('DISTRIBUIDOR', 'Distribuidor'), ('OTRO', 'Otro'), ('', 'No especificado')], default='', help_text='Tipo de cliente', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Nombre del contacto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, help_text='Provincia', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_id',
            field=models.CharField(blank=True, help_text='CUIT/DNI para facturación', max_length=20, null=True),
        ),
    ]
