# Generated by Django 6.0.1 on 2026-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customuser_address_customuser_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, help_text='Proveedor del producto (solo admin)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está visible en el catálogo'),
        ),
    ]
